version: '3'
services:
  media:
    build: .
    restart: unless-stopped
    ports:
      - '24042:24042'
      - '24052:24052'
    volumes:
      - .:/home/node/media
      - ./media:/facile/media
    entrypoint: 'npm run local'
    networks:
      - facile
networks:
  facile:
    external:
      name: facile
