version: '3'
services:
  media:
    build: .
    restart: always
    ports:
      - '24042:24042'
    volumes:
      - .:/home/node/media
      - ./media:/home/node/media/media
    networks:
      - facile
networks:
  facile:
    external:
      name: facile
